# --------------------------
# Site settings
# --------------------------
locale: "en-US"
title: "Xianzhong Ding"
title_separator: "-"
name: &name "Xianzhong Ding"
description: &description "personal description"

url: "https://dingxianzhong.github.io"   # no trailing slash for correct link building
baseurl: ""                               # empty for user site
repository: "dingxianzhong/dingxianzhong.github.io"

# Theme (AcademicPages uses Minimal Mistakes via remote theme)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# --------------------------
# Comments (disabled by default)
# --------------------------
comments:
  provider:

staticman:
  allowedFields: ['name','email','url','message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: "comment-{@timestamp}"
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name','email','message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"

atom_feed:
  path:

# --------------------------
# SEO & Social
# --------------------------
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:

social:
  type: Person
  name: "Xianzhong Ding"
  links: []

# --------------------------
# Analytics (optional)
# --------------------------
analytics:
  provider: "google-universal"
  google:
    tracking_id:

# --------------------------
# Author
# --------------------------
author:
  name: "Xianzhong Ding"
  avatar: "profile.jpeg"
  bio: ""
  location: "Mountain View, CA"
  employer:
  pubmed:
  googlescholar: "https://scholar.google.com/citations?user=lUNyhjwAAAAJ&hl=en"
  email: "contactdingxz@gmail.com"
  github: "dingxianzhong"
  linkedin: "ding-xianzhong-0b5aa9126/"

# --------------------------
# Reading / Build
# --------------------------
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# --------------------------
# Markdown & Conversion
# --------------------------
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# --------------------------
# Collections
# --------------------------
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# --------------------------
# Defaults
# --------------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# --------------------------
# Sass
# --------------------------
sass:
  sass_dir: _sass
  style: compressed

# --------------------------
# Output
# --------------------------
permalink: /:categories/:title/
timezone: America/Los_Angeles

# --------------------------
# Plugins (GitHub Pages–compatible)
# --------------------------
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
